const data = {
    a:{
        pos:{
            x:50,
            y:50,
        },
        operation:'AND',
        input:{
            a:{
                value:false,
                source:null
            },
            b:{
                value:false,
                source:null
            },
        },
        output:true
    },
    b:{
        pos:{
            x:50,
            y:200,
        },
        operation:'AND',
        input:{
            a:{
                value:false,
                source:null
            },
            b:{
                value:false,
                source:null
            },
        },
        output:true
    },
    c:{
        pos:{
            x:250,
            y:125,
        },
        operation:'AND',
        input:{
            a:{
                value:false,
                source:'a'
            },
            b:{
                value:false,
                source:'b'
            },
        },
        output:true
    },
    d:{
        pos:{
            x:350,
            y:350,
        },
        operation:'AND',
        input:{
            a:{
                value:false,
                source:null
            },
            b:{
                value:false,
                source:null
            },
        },
        output:true
    },
    e:{
        pos:{
            x:150,
            y:350,
        },
        operation:'AND',
        input:{
            a:{
                value:false,
                source:null
            },
            b:{
                value:false,
                source:null
            },
        },
        output:true
    },
}

export default data